### PR TITLE
Model for county-level prevalence

### PR DESCRIPTION
**Pull request by sbfnk**

### CODE REVIEW

**Comment by seabbs** [comment]
A few places with very high population density likely causing a skew in that relationship. 

Screenshot 2021-01-22 at 17 09 17

**Comment by seabbs** [comment]
Likewise for income. 

```
> prev %>% arrange(desc(income))
# A tibble: 72 x 10
   county          region            attendance_2 positive_2 pilot mean_age pop_dens unemp_rate proportion_roma income
   <chr>           <chr>                    <dbl>      <dbl> <lgl>    <dbl>    <dbl>      <dbl>           <dbl>  <dbl>
 1 Bratislava      Bratislavský kraj       291789        977 FALSE    0.477   6.93       -0.983          -0.948  3.11 
 2 Malacky         Bratislavský kraj        54657        285 FALSE   -0.478  -0.268      -0.770          -0.153  3.11 
 3 Pezinok         Bratislavský kraj        45801        240 FALSE   -0.497   0.144      -0.849          -0.944  3.11 
 4 Senec           Bratislavský kraj        66052        314 FALSE   -1.58    0.474      -0.577          -0.943  3.11 
 5 Dunajská Streda Trnavský kraj            87329        840 FALSE    0.280  -0.114      -0.505          -0.577  0.666
 6 Galanta         Trnavský kraj            71243        349 FALSE    0.428   0.0277     -1.00           -0.518  0.666
 7 Hlohovec        Trnavský kraj            28892        171 FALSE    0.539   0.122      -1.16           -0.545  0.666
 8 Piešťany        Trnavský kraj            40122        183 FALSE    1.16    0.107      -1.03           -0.809  0.666
 9 Senica          Trnavský kraj            40675        384 FALSE    0.349  -0.224      -0.261          -0.427  0.666
10 Skalica         Trnavský kraj            29223        368 FALSE    0.238  -0.0359     -0.865          -0.582  0.666
```

**Comment by seabbs** [comment]
Data relationships with extreme values scrubbed out. 

Screenshot 2021-01-22 at 17 38 09

**Comment by seabbs** [comment]
`ms.R` is missing in `county_table`.

**Comment by sbfnk** [comment]
It's fixed in master (but will probably need to update how regression results are pulled in)

**Comment by seabbs** [comment]
all the changes in `regression()` look sensible to me.

**Pull request merged**
